### ISSUE TITLE
系统管理中的版本显示建议

### ISSUE THREAD

**Issue by trawor** [FlowCI/flow-web#40]
![2017-11-08 11 10 37](https://user-images.githubusercontent.com/72015/32529864-da93af50-c475-11e7-964f-f5228b894805.png)

1. 添加Web的版本 方便反馈描述
2. 添加一栏Git Hash的信息, 并且点击可以直接跳到相应的github项目commit页面, 如果能diff这个版本和master版本的不同就更好了

**Comment by qhfir** [comment]
赞，这个会加上去。
